# Generated by Django 5.0.4 on 2024-04-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="add",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catagoryid", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("element_id", models.CharField(max_length=100)),
                ("neo4j_id", models.IntegerField()),
                ("avg_age", models.IntegerField()),
                ("avg_book_rating", models.FloatField()),
                ("author", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=20)),
                ("image_url", models.URLField()),
                ("publisher", models.CharField(max_length=100)),
                ("year_of_publication", models.IntegerField()),
                ("category_id", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
