# Generated by Django 5.0.4 on 2024-04-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="add",
            old_name="catagoryid",
            new_name="category_id",
        ),
        migrations.AlterField(
            model_name="add",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
