# Generated by Django 5.0.4 on 2024-04-12 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_rename_catagoryid_add_category_id_alter_add_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="add",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="add",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
