# Generated by Django 5.0.4 on 2024-04-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_add_created_at_alter_add_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="add",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
