# Generated by Django 5.0.4 on 2024-04-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_alter_add_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="catagories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_id", models.IntegerField()),
                ("category_name", models.CharField(max_length=100)),
            ],
        ),
    ]
