# Generated by Django 5.0.4 on 2024-05-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_booklike_bookvisited"),
    ]

    operations = [
        migrations.CreateModel(
            name="agee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Gid", models.IntegerField()),
                ("Gage", models.IntegerField()),
                ("Gyear", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="getvisited",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Gid", models.IntegerField()),
                ("Gage", models.IntegerField()),
                ("Gyear", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
