# Generated by Django 5.0.4 on 2024-05-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_rename_users_usersmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UsersModel",
        ),
        migrations.RemoveField(
            model_name="person",
            name="age",
        ),
        migrations.AddField(
            model_name="person",
            name="password",
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
