# Generated by Django 5.0.4 on 2024-05-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_delete_usersmodel_remove_person_age_person_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
