# Generated by Django 5.0.4 on 2024-05-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_person_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="add",
            name="userid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booklike",
            name="userid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bookvisited",
            name="userid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="catagories",
            name="userid",
            field=models.IntegerField(default=0),
        ),
    ]
