# Generated by Django 5.0.4 on 2024-05-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
